### ISSUE TITLE
Errato calcolo IVA

### ISSUE THREAD

**Issue by Buseppe** [riddik14/hassio-package-consumi#3]
Ciao, 

ho notato che il calcolo dell'iva probabilmente è errato all'interno del file pkg_tariffe_luce_consumi.yaml.

infatti, provando il package, ho notato che il volore dell'iva risultava troppo alto.

Il calcola fatto nel package è           {%set iva = ( energia + trasporto * (states.input_number.iva.state | float) / 100) %}

che andrebbe modificato in           {%set iva = ( (energia + trasporto) * (states.input_number.iva.state | float) / 100) %}

Prima sommare l'energia ed il trasporto e poi moltiplicare per il valore dell'iva e dividere per 100.

Complimenti per il package.

**Comment by riddik14** [comment]
corretto. grazie
