### ISSUE TITLE
Configurazione non valida

### ISSUE THREAD

**Issue by ilnonno70** [riddik14/hassio-package-consumi#4]
Ciao, ho provato a impostare il package del monitoraggio consumi.
Ho inserito alla riga 19 il mio sensore dei W e salvato il tutto.
Prima di Riavviare, quando sui controlli del server faccio una verifica della configurazione, mi restituisce l'errore che vedi in foto.
![Cattura](https://user-images.githubusercontent.com/73182921/101387901-6f2c1100-38bf-11eb-84ff-55b0808c0189.JPG)
Da cosa dipende?

Grazie.

**Comment by riddik14** [comment]
Hai un doppio Boolean con lo stesso nome, controlla il tuo configuration.yaml
