### ISSUE TITLE
come impostare lo shelly

### ISSUE THREAD

**Issue by Boogs77** [riddik14/hassio-package-consumi#5]
Salve.
Ho uno shelly EM è ho utilizzato il tuo convertitore sensor.energia_kwh inserendo come _sensore_misura_energia2_ la potenza istantanea in W rilevata dallo shelly.
Ottengo però 

1. Un valore di consumo_giornaliero superiore a quello mensile
2. I Consumi giornalieri delle varie Fascia 1 e 2 in W, mentre il consumo_totale_oggi in KWh
3. Di conseguenza anche i costi giornalieri non sono corretti. 

Ho aggiornato dalla prima versione oggi stesso nel tentativo di risolvere il problema del consumo giornaliero spropositato.

**Comment by riddik14** [comment]
![image](https://user-images.githubusercontent.com/37450907/101489414-347ab500-3961-11eb-87c9-168ef4e329fe.jpeg)![image](https://user-images.githubusercontent.com/37450907/101489415-347ab500-3961-11eb-8780-b6b58e18d9f6.jpeg)

A sensore togli il commento # e cancella il sensore a sinistra del
Cancelletto 

Segui la foto e dove vedi sensor.ripostiglio_energy_power metti il tuo sensore

**Comment by Boogs77** [comment]
.

**Comment by Boogs77** [comment]
`    ##--------------------- IMPOSTAZIONI DEL PACKAGE ---------------------##
      setting:

        #Sensore: &sensore_misura_energia 
        Sensore_wh_to_kwh: &sensore_misura_energia sensor.shelly_shem_b9ec16_1_current_consumption
        TariffaF1: &tariffaf1 0.0979
        TariffaF2: &tariffaf2 0.0546
        TariffaF3: &tariffaf3 0.0546
        Accisa: &accisa 0.0227           #calcolo medio sulla bolletta
        Iva: &iva 10                     #IVA
        trasporto: &trasporto 0.07224    #calcolo medio sulla bolletta
        
    ##--------------------- IMPOSTAZIONI DEL PACKAGE ---------------------##   `
Ho eliminato il primo sensore, ma ho dovuto rinominare il riferimenti al sensore_misura_energia2 e cancellare la parte relativa alla conversione.
Il problema è rimasto.

**Comment by riddik14** [comment]
Forse stai sbagliando sensore watt
Dovresti avere watt e w/h. Devi usare watt che ti mostra i valori istantanei

**Comment by Boogs77** [comment]
Sto usando quello. Potenza istantanea in W

**Comment by riddik14** [comment]
Puoi configurare sotto mqtt un ulteriore sensore per lo shelly e prendi i dati da lì

**Comment by Boogs77** [comment]
ho provato in velocità cambiando il nuovo file.
Ottengo:

`duplicated mapping key at line 524, columm -158:
  input_select`

**Comment by riddik14** [comment]
Riscarica il pacchetto nuovo

**Comment by Boogs77** [comment]
È il file del pacchetto nuovo

**Comment by riddik14** [comment]
grazie per la correzione
puoi fare un reset dal menu sviluppatore di hassio sotto servizi
servizio "utility_meter.calibrate"

Dati di Servizio (YAML, opzionale)
entity_id: sensor.consumo_annuale_f1
value: 0
