### ISSUE TITLE
Errore in Lovelace

### ISSUE THREAD

**Issue by jokerigno** [riddik14/hassio-package-consumi#9]
Ciao,

ho appena fatto l'upgrade (scheda con secret e nuovo lovelace).

Su quest'ultimo ho notato un paio di stranezze:

![image](https://user-images.githubusercontent.com/23552762/104852096-09d53200-58f9-11eb-98d6-fe74a3c44703.png)

La prima è che c'è il tuo avatar nell'orario fascia 1 (e non credo fosse tua intenzione metterlo lì).

La seconda è che è scomparso il bottone per cambiare le impostazioni (ma continua a funzionare - ho lasciato la vecchia scheda).

Ciao!

**Comment by riddik14** [comment]
Beh l'avatar li è come una firma😂. Le impostazioni non servono perché compili il secret che serve per fare aggiornamenti e non cancellare ogni volta i dati. Comunque non serviva aprire un problema per comunicarmi questo, potevi dirlo anche sul gruppo Telegram. Saluti

**Comment by riddik14** [comment]
Però stranamente vedi ancora il setup fasce orarie che attualmente ho tolto. Controlla il tuo Lovelace che sia l'ultimo. 

![image](https://user-images.githubusercontent.com/37450907/104852587-29218e80-58fc-11eb-9271-5432839f8af0.jpeg)
